### ISSUE TITLE
Uncorrect use of logging functions in 'controller.py'

### ISSUE THREAD

**Issue by RemiRigal** [Arnacke/Hexabot#24]
Uncorrect use of logging functions in [controller.py](https://github.com/Arnacke/Hexabot/blob/master/workspaceRos/src/phantomx/phantomx_mission_completion/src/controller.py).

The function `rospy.logwarn` should not be used to log data for debugging. Please use `rospy.logdebug` instead.
A better approach is to publish these data into a topic so that it can retrieved easily on demand and displayed with ROS tools.

**Comment by Arnacke** [comment]
Issue solved by #28

**Comment by RemiRigal** [comment]
No

**Comment by Arnacke** [comment]
Yes  #31
