### ISSUE TITLE
Publisher instantiated before subscriber in 'controller.py'

### ISSUE THREAD

**Issue by RemiRigal** [Arnacke/Hexabot#25]
In the script `controller.py`, the variables `cmd` and `error` are used in the subscriber's callback `lidarRead` initialized before them, it might happen that they are referenced before initialization.

Related code:
```python
scan = rospy.Subscriber("/phantomx/lidar", LaserScan, lidarRead)
cmd = rospy.Publisher("/phantomx/cmd_vel",Twist, queue_size=5)
vel_msg.linear.x = 0.6
error = 0
```

**Comment by Arnacke** [comment]
Issue solved by #28
