### ISSUE TITLE
Error with phantomx_crackMap (process has died)

### ISSUE THREAD

**Issue by TilletJ** [Arnacke/Hexabot#50]
I got this error:

![image](https://user-images.githubusercontent.com/17474707/73337635-058db000-4275-11ea-900f-68025c28a8b6.png)

It seems to be linked with the number of outputs of cv2.findContours depending on the version of OpenCV used.
I use this version:
`>>> cv2.\_\_version\_\_

'3.2.0'`

**Comment by Arnacke** [comment]
Trouble was fixed by #49
